from . import rental_coefficient_type
from . import rental_coefficient_table
from . import rental_coefficient_table_line
from . import rental_dynamic_pricing_table
from . import rental_dynamic_pricing_table_line
from . import rental_product_warehouse_pricing_config
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
