from . import account_move
from . import res_company
from . import res_config_settings
from . import product_product
from . import rental_set_component
from . import product_template
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import stock_picking
from . import stock_picking_type
