from . import test_product_config
from . import test_rental_flow_profile
from . import test_rental_dossier
from . import test_mcrf_service
from . import test_order_generation
from . import test_payment_preparation
from . import test_payment_orchestration
from . import test_event_integration
from . import test_confirmation_email
from . import test_ticket_service
from . import test_kiosk_lookup
from . import test_kiosk_order
from . import test_i18n
